- id: '1707341317094'
  alias: Dimmer switch v1 light control
  description: ''
  use_blueprint:
    path: dimmer_switch/light_control.yaml
    input:
      dimmer_switch_device: ec67b101fb73db337152101cdfa3d798
      entity_targets:
      - light.office_desk
      - light.tischlampe
